# Generated by Django 4.2.30 on 2026-05-05 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_examtype_category_examtype_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYearEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_study', models.IntegerField(choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4'), (5, 'Year 5')])),
                ('semester_number', models.IntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2')])),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('repeated', 'Repeated'), ('deferred', 'Deferred'), ('withdrawn', 'Withdrawn')], default='active', max_length=20)),
                ('enrollment_date', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='year_enrollments', to='academics.academicsession')),
                ('enrolled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolled_students', to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='year_enrollments', to='academics.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='year_enrollments', to='students.student')),
            ],
            options={
                'verbose_name': 'Academic Year Enrollment',
                'verbose_name_plural': 'Academic Year Enrollments',
                'ordering': ['-academic_session__name', 'year_of_study', 'semester_number'],
                'unique_together': {('student', 'academic_session', 'year_of_study', 'semester_number')},
            },
        ),
        migrations.AddField(
            model_name='enrollment',
            name='academic_year_enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_enrollments', to='students.academicyearenrollment'),
        ),
    ]
