# Generated by Django 4.2.30 on 2026-05-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_academicyearenrollment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='current_level',
        ),
        migrations.AddField(
            model_name='student',
            name='current_semester_number',
            field=models.IntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2')], default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='current_year',
            field=models.IntegerField(choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4'), (5, 'Year 5')], default=1),
        ),
    ]
