# Generated by Django 4.2.30 on 2026-05-05 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_academicsession_year_end_academicsession_year_start_and_more'),
        ('students', '0003_remove_student_current_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionapplication',
            name='intake',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='academics.intake'),
        ),
        migrations.AddField(
            model_name='student',
            name='intake',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.intake'),
        ),
    ]
