# Generated by Django 4.2.30 on 2026-05-05 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_studysemester_studyyear'),
        ('students', '0004_admissionapplication_intake_student_intake'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicyearenrollment',
            options={'ordering': ['-academic_session__name', 'year_of_study__level', 'semester_number__number'], 'verbose_name': 'Academic Year Enrollment', 'verbose_name_plural': 'Academic Year Enrollments'},
        ),
        migrations.AlterField(
            model_name='academicyearenrollment',
            name='semester_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='semester_enrollments', to='academics.studysemester'),
        ),
        migrations.AlterField(
            model_name='academicyearenrollment',
            name='year_of_study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='year_enrollments', to='academics.studyyear'),
        ),
        migrations.AlterField(
            model_name='student',
            name='current_semester_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.studysemester'),
        ),
        migrations.AlterField(
            model_name='student',
            name='current_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.studyyear'),
        ),
    ]
