# Generated by Django 4.2.30 on 2026-05-05 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_alter_academiccalendarevent_semester_and_more'),
        ('students', '0005_alter_academicyearenrollment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicyearenrollment',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='year_enrollments', to='academics.studysemester'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academics.studysemester'),
        ),
    ]
