# Generated by Django 4.2.30 on 2026-05-06 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_academicyearenrollment_semester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='is_retake',
            field=models.BooleanField(default=False, help_text='Mark if this is a retake of a previously failed course'),
        ),
    ]
