# Generated by Django 4.2.30 on 2026-05-05 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_alter_academiccalendarevent_semester_and_more'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.studysemester'),
        ),
    ]
