# Generated by Django 4.2.30 on 2026-05-06 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_academicyearenrollment_semester_and_more'),
        ('academics', '0014_delete_semester'),
        ('finance', '0002_alter_invoice_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestructure',
            name='frequency',
            field=models.CharField(choices=[('per_semester', 'Per Semester'), ('per_year', 'Per Year'), ('once', 'Once'), ('graduation', 'Graduation'), ('monthly', 'Monthly')], default='per_semester', max_length=20),
        ),
        migrations.CreateModel(
            name='StudentFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('fee_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to='finance.feestructure')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.academicsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_fees', to='students.student')),
            ],
            options={
                'ordering': ['-assigned_date'],
                'unique_together': {('student', 'fee_structure', 'session')},
            },
        ),
    ]
