# Generated by Django 4.2.30 on 2026-05-09 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_feestructure_frequency_studentfee'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_items', to='finance.invoiceitem')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_items', to='finance.payment')),
            ],
            options={
                'unique_together': {('payment', 'invoice_item')},
            },
        ),
    ]
