# Generated by Django 4.2.30 on 2026-05-09 08:47

from django.db import migrations


def create_default_currencies(apps, schema_editor):
    """Create default currencies."""
    Currency = apps.get_model('finance', 'Currency')
    
    # Create UGX as default currency
    ugx = Currency.objects.create(
        code='UGX',
        name='Ugandan Shilling',
        symbol='UGX',
        is_default=True,
        exchange_rate_to_default=1.0000,
        is_active=True
    )
    
    # Create other common currencies
    Currency.objects.create(
        code='USD',
        name='US Dollar',
        symbol='$',
        is_default=False,
        exchange_rate_to_default=0.00027,  # Approximate rate
        is_active=True
    )
    
    Currency.objects.create(
        code='EUR',
        name='Euro',
        symbol='€',
        is_default=False,
        exchange_rate_to_default=0.00025,  # Approximate rate
        is_active=True
    )
    
    Currency.objects.create(
        code='GBP',
        name='British Pound',
        symbol='£',
        is_default=False,
        exchange_rate_to_default=0.00021,  # Approximate rate
        is_active=True
    )


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_currency_studentcurrency_programmecurrency_and_more'),
    ]

    operations = [
        migrations.RunPython(create_default_currencies),
    ]
