# Generated by Django 4.2.30 on 2026-05-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0017_alter_programme_level'),
        ('finance', '0006_setup_default_currencies'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feestructure',
            options={'ordering': ['fee_type', 'name'], 'verbose_name': 'Fee Structure', 'verbose_name_plural': 'Fee Structures'},
        ),
        migrations.RemoveField(
            model_name='feestructure',
            name='programme',
        ),
        migrations.AddField(
            model_name='feestructure',
            name='faculties',
            field=models.ManyToManyField(blank=True, help_text='Leave empty to apply to all faculties', related_name='fees', to='academics.faculty'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='programmes',
            field=models.ManyToManyField(blank=True, help_text='Leave empty to apply to all programmes', related_name='fees', to='academics.programme'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='schedules',
            field=models.JSONField(blank=True, default=list, help_text="List of schedules this fee applies to (e.g., ['fulltime', 'weekend']). Leave empty for all."),
        ),
    ]
