# Generated by Django 4.2.20 on 2026-05-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0017_alter_programme_level'),
        ('finance', '0007_fee_structure_many_to_many'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestructure',
            name='courses',
            field=models.ManyToManyField(blank=True, help_text='Leave empty to apply to all courses', related_name='fees', to='academics.course'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='departments',
            field=models.ManyToManyField(blank=True, help_text='Leave empty to apply to all departments', related_name='fees', to='academics.department'),
        ),
    ]
