# Generated by Django 4.2.30 on 2026-05-04 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=20, unique=True)),
                ('staff_type', models.CharField(choices=[('academic', 'Academic Staff'), ('non_academic', 'Non-Academic Staff'), ('administrative', 'Administrative Staff')], default='academic', max_length=20)),
                ('rank', models.CharField(blank=True, choices=[('professor', 'Professor'), ('associate_professor', 'Associate Professor'), ('senior_lecturer', 'Senior Lecturer'), ('lecturer_i', 'Lecturer I'), ('lecturer_ii', 'Lecturer II'), ('assistant_lecturer', 'Assistant Lecturer'), ('graduate_assistant', 'Graduate Assistant')], max_length=30)),
                ('qualification', models.CharField(blank=True, max_length=200)),
                ('specialization', models.CharField(blank=True, max_length=200)),
                ('date_employed', models.DateField(blank=True, null=True)),
                ('contract_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract')], default='full_time', max_length=20)),
                ('max_workload', models.IntegerField(default=18, help_text='Maximum credit units per semester')),
                ('office_location', models.CharField(blank=True, max_length=100)),
                ('research_interests', models.TextField(blank=True)),
                ('publications', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='academics.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['staff_id'],
            },
        ),
        migrations.CreateModel(
            name='StaffPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teaching_score', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('research_score', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('community_score', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('attendance_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('overall_rating', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.semester')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_records', to='staff.staffprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('staff', 'semester')},
            },
        ),
    ]
