# Generated by Django 4.2.30 on 2026-05-05 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_alter_academiccalendarevent_semester_and_more'),
        ('staff', '0003_payroll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffperformance',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.studysemester'),
        ),
    ]
