from django.urls import path
from . import views

app_name = 'academics'

urlpatterns = [
    path('study-levels/', views.study_level_list, name='study_level_list'),
    path('study-levels/create/', views.study_level_create, name='study_level_create'),
    path('study-levels/<int:pk>/edit/', views.study_level_edit, name='study_level_edit'),
    path('study-levels/<int:pk>/delete/', views.study_level_delete, name='study_level_delete'),
    path('departments/', views.department_list, name='department_list'),
    path('departments/create/', views.department_create, name='department_create'),
    path('departments/<int:pk>/edit/', views.department_edit, name='department_edit'),
    path('departments/<int:pk>/delete/', views.department_delete, name='department_delete'),
    path('departments/<int:pk>/', views.department_detail, name='department_detail'),
    path('programmes/', views.programme_list, name='programme_list'),
    path('programmes/create/', views.programme_create, name='programme_create'),
    path('programmes/<int:pk>/edit/', views.programme_edit, name='programme_edit'),
    path('programmes/<int:pk>/delete/', views.programme_delete, name='programme_delete'),
    path('programmes/<int:pk>/', views.programme_detail, name='programme_detail'),
    path('programmes/<int:pk>/courses/', views.programme_courses, name='programme_courses'),
    path('courses/', views.course_list, name='course_list'),
    path('courses/create/', views.course_create, name='course_create'),
    path('courses/<int:pk>/edit/', views.course_create, name='course_edit'),
    path('courses/<int:pk>/allocations/manage/', views.course_allocation_popup, name='course_allocation_popup'),
    path('courses/<int:pk>/', views.course_detail, name='course_detail'),
    path('courses/<int:pk>/remove/', views.course_remove, name='course_remove'),
    path('add-existing-course/', views.add_existing_course_to_programme, name='add_existing_course_to_programme'),
    path('sessions/', views.session_list, name='session_list'),
    path('sessions/create/', views.session_create, name='session_create'),
    path('sessions/<int:pk>/edit/', views.session_edit, name='session_edit'),
    path('sessions/<int:pk>/delete/', views.session_delete, name='session_delete'),
    path('sessions/<int:pk>/set-current/', views.session_set_current, name='session_set_current'),
    path('intakes/', views.intake_list, name='intake_list'),
    path('intakes/create/', views.intake_create, name='intake_create'),
    path('intakes/<int:pk>/edit/', views.intake_edit, name='intake_edit'),
    path('intakes/<int:pk>/delete/', views.intake_delete, name='intake_delete'),
    path('intakes/<int:pk>/', views.intake_detail, name='intake_detail'),
    path('faculties/', views.faculty_list, name='faculty_list'),
    path('faculties/create/', views.faculty_create, name='faculty_create'),
    path('faculties/<int:pk>/edit/', views.faculty_edit, name='faculty_edit'),
    path('faculties/<int:pk>/delete/', views.faculty_delete, name='faculty_delete'),
    path('faculties/<int:pk>/', views.faculty_detail, name='faculty_detail'),
    path('campuses/', views.campus_list, name='campus_list'),
    path('campuses/create/', views.campus_create, name='campus_create'),
    path('campuses/<int:pk>/edit/', views.campus_edit, name='campus_edit'),
    path('campuses/<int:pk>/delete/', views.campus_delete, name='campus_delete'),
    path('grades/', views.grade_management, name='grade_management'),
    path('grades/enter/<int:allocation_id>/', views.enter_results, name='enter_results'),
    path('attendance/', views.attendance_list, name='attendance_list'),
    path('attendance/take/<int:allocation_id>/', views.take_attendance, name='take_attendance'),
    path('timetable/', views.my_timetable, name='my_timetable'),
]
