# Generated by Django 4.2.30 on 2026-05-05 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_campus_programme_schedule_faculty_campus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
