# Generated by Django 4.2.30 on 2026-05-05 08:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_alter_campus_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicsession',
            options={'ordering': ['-name']},
        ),
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ['-session__name', 'semester_type']},
        ),
        migrations.RemoveField(
            model_name='academicsession',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='academicsession',
            name='start_date',
        ),
        migrations.AddField(
            model_name='academicsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
