# Generated by Django 4.2.30 on 2026-05-05 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0005_remove_academicsession_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtype',
            name='category',
            field=models.CharField(choices=[('continuous', 'Continuous Assessment'), ('midterm', 'Midterm'), ('final', 'Final Exam'), ('coursework', 'Coursework'), ('resit', 'Resit / Supplementary'), ('practical', 'Practical')], default='continuous', max_length=20),
        ),
        migrations.AddField(
            model_name='examtype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='examtype',
            name='max_score',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='approval_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted by Lecturer'), ('hod_approved', 'Approved by HOD'), ('registrar_approved', 'Approved by Registrar'), ('published', 'Published'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='approved_by_hod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hod_approved_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='approved_by_registrar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrar_approved_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='hod_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='is_resit',
            field=models.BooleanField(default=False, help_text='Is this a resit/supplementary result?'),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='registrar_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='examtype',
            name='weight',
            field=models.DecimalField(decimal_places=2, help_text='Percentage weight (e.g. 30 for 30%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AcademicCalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('holiday', 'Public Holiday'), ('exam_period', 'Exam Period'), ('registration', 'Registration Deadline'), ('course_add', 'Course Add Deadline'), ('course_drop', 'Course Drop Deadline'), ('graduation', 'Graduation'), ('orientation', 'Orientation'), ('other', 'Other')], default='other', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='academics.semester')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='academics.academicsession')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='ExamScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_scores', to='academics.courseallocation')),
                ('exam_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='academics.examtype')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_scores', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_scores', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('student', 'course_allocation', 'exam_type')},
            },
        ),
    ]
