# Generated by Django 4.2.30 on 2026-05-05 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_examtype_category_examtype_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicsession',
            name='year_end',
            field=models.IntegerField(blank=True, help_text='e.g. 2027', null=True),
        ),
        migrations.AddField(
            model_name='academicsession',
            name='year_start',
            field=models.IntegerField(blank=True, help_text='e.g. 2026', null=True),
        ),
        migrations.CreateModel(
            name='Intake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Auto-generated if left blank', max_length=100)),
                ('intake_period', models.CharField(choices=[('january', 'January'), ('march', 'March'), ('may', 'May'), ('august', 'August'), ('september', 'September'), ('october', 'October')], max_length=20)),
                ('intake_date', models.DateField(help_text='First day of this intake')),
                ('closing_date', models.DateField(blank=True, help_text='Application closing date', null=True)),
                ('orientation_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('max_capacity', models.IntegerField(blank=True, help_text='Max students for this intake', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intakes', to='academics.academicsession')),
            ],
            options={
                'verbose_name': 'Intake',
                'verbose_name_plural': 'Intakes',
                'ordering': ['-academic_session__name', 'intake_period'],
                'unique_together': {('academic_session', 'intake_period')},
            },
        ),
    ]
