# Generated by Django 4.2.30 on 2026-05-05 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_academicsession_year_end_academicsession_year_start_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intake',
            options={'ordering': ['-created_at'], 'verbose_name': 'Intake', 'verbose_name_plural': 'Intakes'},
        ),
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterUniqueTogether(
            name='intake',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='intake',
            name='code',
            field=models.CharField(default=1, help_text='e.g. AUG2026, JAN2027', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='semester',
            name='name',
            field=models.CharField(blank=True, help_text='e.g. Semester 1 2026/2027', max_length=100),
        ),
        migrations.AlterField(
            model_name='intake',
            name='academic_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intakes', to='academics.academicsession'),
        ),
        migrations.AlterField(
            model_name='intake',
            name='name',
            field=models.CharField(help_text='e.g. August 2026 Intake', max_length=100),
        ),
        migrations.AlterField(
            model_name='semester',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semesters', to='academics.academicsession'),
        ),
        migrations.RemoveField(
            model_name='intake',
            name='closing_date',
        ),
        migrations.RemoveField(
            model_name='intake',
            name='intake_date',
        ),
        migrations.RemoveField(
            model_name='intake',
            name='intake_period',
        ),
        migrations.RemoveField(
            model_name='intake',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='intake',
            name='max_capacity',
        ),
        migrations.RemoveField(
            model_name='intake',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='intake',
            name='orientation_date',
        ),
    ]
