# Generated by Django 4.2.30 on 2026-05-05 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_alter_intake_options_alter_semester_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='semester',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='registration_deadline',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='start_date',
        ),
    ]
