# Generated by Django 4.2.30 on 2026-05-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_alter_semester_options_remove_semester_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicsession',
            name='year_end',
        ),
        migrations.RemoveField(
            model_name='academicsession',
            name='year_start',
        ),
        migrations.RemoveField(
            model_name='intake',
            name='academic_session',
        ),
        migrations.AlterField(
            model_name='academicsession',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
