# Generated by Django 4.2.30 on 2026-05-05 14:13

from django.db import migrations, models
import django.db.models.deletion


def clear_course_semester_values(apps, schema_editor):
    """Clear old string values from course.semester before FK conversion."""
    Course = apps.get_model('academics', 'Course')
    Course.objects.filter(semester__isnull=False).update(semester=None)


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_remove_academicsession_year_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.RunPython(clear_course_semester_values, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='semester',
            name='semester_type',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='session',
        ),
        migrations.AddField(
            model_name='semester',
            name='code',
            field=models.CharField(default=1, help_text='e.g. SEM2026-1, SEM2026-2', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='academics.semester'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='name',
            field=models.CharField(help_text='e.g. Semester 1 2026/2027', max_length=100),
        ),
    ]
