# Generated by Django 4.2.30 on 2026-05-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_remove_semester_semester_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudySemester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g. S1, S2', max_length=10, unique=True)),
                ('name', models.CharField(help_text='e.g. Semester 1, Semester 2', max_length=50)),
                ('number', models.IntegerField(help_text='e.g. 1 for Semester 1, 2 for Semester 2', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='StudyYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g. Y1, Y2, Y3', max_length=10, unique=True)),
                ('name', models.CharField(help_text='e.g. Year 1, Year 2', max_length=50)),
                ('level', models.IntegerField(help_text='e.g. 1 for Year 1, 2 for Year 2', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['level'],
            },
        ),
    ]
