# Generated by Django 4.2.30 on 2026-05-05 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_studysemester_studyyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academiccalendarevent',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='academics.studysemester'),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='academics.studysemester'),
        ),
        migrations.AlterField(
            model_name='courseallocation',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='academics.studysemester'),
        ),
    ]
