# Generated by Django 4.2.30 on 2026-05-05 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_academicyearenrollment_semester_and_more'),
        ('finance', '0002_alter_invoice_semester'),
        ('academics', '0013_alter_academiccalendarevent_semester_and_more'),
        ('staff', '0004_alter_staffperformance_semester'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Semester',
        ),
    ]
