# Generated by Django 4.2.30 on 2026-05-07 06:22

from django.db import migrations, models


def create_study_levels(apps, schema_editor):
    """Create StudyLevel records for existing programme levels."""
    StudyLevel = apps.get_model('academics', 'StudyLevel')
    
    levels = [
        {'code': 'CERT', 'name': 'Certificate', 'level_number': 1, 'description': 'Certificate programme'},
        {'code': 'DIP', 'name': 'Diploma', 'level_number': 2, 'description': 'Diploma programme'},
        {'code': 'BSC', 'name': "Bachelor's Degree", 'level_number': 3, 'description': 'Undergraduate bachelor degree'},
        {'code': 'MSC', 'name': "Master's Degree", 'level_number': 4, 'description': 'Postgraduate master degree'},
        {'code': 'PHD', 'name': 'PhD', 'level_number': 5, 'description': 'Doctor of Philosophy'},
    ]
    
    for level_data in levels:
        StudyLevel.objects.create(**level_data)


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_delete_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. Certificate, Diploma, Bachelor's Degree", max_length=50, unique=True)),
                ('code', models.CharField(help_text='e.g. CERT, DIP, BSC, MSC, PHD', max_length=20, unique=True)),
                ('level_number', models.IntegerField(help_text="e.g. 1 for Certificate, 2 for Diploma, 3 for Bachelor's, etc.", unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Study Level',
                'verbose_name_plural': 'Study Levels',
                'ordering': ['level_number'],
            },
        ),
        migrations.RunPython(create_study_levels, migrations.RunPython.noop),
    ]
