# Generated by Django 4.2.30 on 2026-05-07 06:24

from django.db import migrations, models
import django.db.models.deletion


def migrate_programme_levels(apps, schema_editor):
    """Migrate existing programmes to use StudyLevel foreign keys."""
    Programme = apps.get_model('academics', 'Programme')
    StudyLevel = apps.get_model('academics', 'StudyLevel')
    
    # Map old level strings to new StudyLevel codes
    level_mapping = {
        'certificate': 'CERT',
        'diploma': 'DIP', 
        'bachelors': 'BSC',
        'masters': 'MSC',
        'phd': 'PHD',
    }
    
    for programme in Programme.objects.all():
        old_level = programme.level
        if old_level in level_mapping:
            study_level = StudyLevel.objects.get(code=level_mapping[old_level])
            programme.level_new = study_level
            programme.save()


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0015_create_study_level_model'),
    ]

    operations = [
        # Add temporary foreign key field
        migrations.AddField(
            model_name='programme',
            name='level_new',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='programmes_new', to='academics.studylevel'
            ),
        ),
        # Migrate data to temporary field
        migrations.RunPython(migrate_programme_levels, migrations.RunPython.noop),
        # Remove old field
        migrations.RemoveField(
            model_name='programme',
            name='level',
        ),
        # Rename temporary field to final name
        migrations.RenameField(
            model_name='programme',
            old_name='level_new',
            new_name='level',
        ),
    ]
