# Generated by Django 4.2.30 on 2026-05-09 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0016_migrate_programme_levels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='programmes', to='academics.studylevel'),
            preserve_default=False,
        ),
    ]
