# Generated by Django 4.2.20 on 2026-06-16 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0018_add_is_current_to_studysemester'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programmes_coordinated', to=settings.AUTH_USER_MODEL),
        ),
    ]
